module.exports = {
    REQUIRE: 'không được để trống!',
    INVALID: 'không hợp lệ!',
    NUMBER: 'phải là số!',
    NOT_KEY: 'Không tìm thấy key hoặc key không hợp lệ!',
    NOT_TYPE: 'Không tìm thấy type hoặc type không hợp lệ!',
    NOT_ID: 'Không tìm thấy ID hoặc ID không hợp lệ!',
    NOT_STATUS: 'Không tìm thấy status hoặc status không hợp lệ!',
    OK_DATA: 'Đã tìm thấy dữ liệu!',
    NOT_DATA: 'Không tìm thấy dữ liệu!',
    ERROR_DATA: 'Lỗi dữ liệu!',
    OK_CREATE: 'Thêm thành công',
    OK_DELETE: 'Xóa thành công',
    OK_EDIT: 'Sửa thành công',
    OK_BIN: 'Xóa vào thùng rác thành công',
    OK_RESTORE: 'Khôi phục thành công',
    OK_ACTIVE: 'Bật hoạt động thành công',
    NOT_ACTIVE: 'Ngưng hoạt động thành công',
    OK_BROWSER: 'Bật duyệt thành công',
    NOT_BROWSER: 'Ngưng duyệt thành công',
    NULL_BODY: 'Lỗi dữ liệu vào không đúng!',
    CHECK_CONFIRMPASSWORD: 'Xác nhận mật khẩu không đúng!',
    NOT_REQUIRE: 'không được để trống!',
    NOT_KEY_USER: 'Tài khoản của bạn đã bị khóa!'
}